package com.bezkoder.spring_boot_jpa_postgresql.mapper;

import java.util.List;

import org.mapstruct.InheritConfiguration;
import org.mapstruct.InjectionStrategy;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.MappingTarget;
import org.mapstruct.ReportingPolicy;

import com.bezkoder.spring_boot_jpa_postgresql.dto.TutorialDto;
import com.bezkoder.spring_boot_jpa_postgresql.model.Tutorial;

@Mapper(componentModel = "spring", uses = { CourseMapper.class, TutorialDetailMapper.class },
        injectionStrategy = InjectionStrategy.CONSTRUCTOR, unmappedTargetPolicy = ReportingPolicy.ERROR)
public interface TutorialMapper {

    // This back reference is already omitted from JSON
    @Mapping(target = "author", ignore = true)
    TutorialDto toDto(Tutorial tutorial);

    // IDs are generated by JPA; relationships keep their existing dedicated endpoints.
    @Mapping(target = "id", ignore = true)
    @Mapping(target = "author", ignore = true)
    @Mapping(target = "courses", ignore = true)
    @Mapping(target = "detail", ignore = true)
    Tutorial toEntity(TutorialDto tutorialDto);

    List<TutorialDto> toDtoList(List<Tutorial> tutorials);

    @InheritConfiguration(name = "toEntity")
    void updateEntityFromDto(TutorialDto tutorialDto, @MappingTarget Tutorial tutorial);
}
